"""with indexes

Revision ID: 373f643cb860
Revises: a07a9b97f09f
Create Date: 2024-11-02 18:22:05.488703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373f643cb860'
down_revision: Union[str, None] = 'a07a9b97f09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_city', 'results', ['city'], unique=False)
    op.create_index('idx_city_result', 'results', ['city', 'result'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_city_result', table_name='results')
    op.drop_index('idx_city', table_name='results')
    # ### end Alembic commands ###
